# Тема "Вычисления с помощью Numpy"

### Задание 1

In [ ]:
import numpy as np
A = np.array([[1, 6],
     [2, 8],
     [3, 11],
     [3, 10],
     [1, 7]])
A

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [ ]:
mean_a = np.mean(A, axis = 0)
mean_a

array([2. , 8.4])

### Задание 2

In [ ]:
a_centered = np.array([A[:, 0] - mean_a[0], A[:, 1] - mean_a[1]]).T 
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

##### Получилось кривовато

### Задание 3

In [ ]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]
result = a_centered_sp/(a_centered.shape[0] - 1)
result

2.0

### Задание 4

In [ ]:
cov = np.cov(A.T)[0, 1]
cov

2.0

# Тема “Работа с данными в Pandas”

### Задание 1

In [ ]:
import pandas as pd
import numpy as np

authors = pd.DataFrame({
    "author_id": [1,2,3],
    "author_name": ['Тургенев','Чехов','Островский']})

book = pd.DataFrame({
    "author_id": [1,1,1,2,2,3,3],
    "book_title": ['Отцы и дети','Рудин','Дворянское гнездо','Толстый и тонкий','Дама с собачкой','Гроза','Таланты и поклонники'],
    "price": [450,300,350,500,450,370,290]})
book.head()

author_id         book_title  price
0          1        Отцы и дети    450
1          1              Рудин    300
2          1  Дворянское гнездо    350
3          2   Толстый и тонкий    500
4          2    Дама с собачкой    450

### Задание 2

In [ ]:
author_price = pd.merge(authors, book, on = 'author_id', how = 'inner')
author_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 3

In [ ]:
top5 = author_price.sort_values(by='price', ascending=False).iloc[0:5, :]
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 4

In [ ]:
author_max = author_price.groupby('author_name').agg({'price':'max'})
author_min = author_price.groupby('author_name').agg({'price':'min'})
author_mean = author_price.groupby('author_name').agg({'price':'mean'})
author_stat = pd.merge(author_max, author_min, on = 'author_name', how = 'inner')
author_stat = pd.merge(author_stat, author_mean, on = 'author_name', how = 'inner')
author_stat = author_stat.reset_index()
author_stat = author_stat.rename(columns={'price_x':'max_price'})
author_stat = author_stat.rename(columns={'price_y':'min_price'})
author_stat = author_stat.rename(columns={'price':'mean_price'})
author_stat

author_name  max_price  min_price  mean_price
0  Островский        370        290  330.000000
1    Тургенев        450        300  366.666667
2       Чехов        500        450  475.000000